apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

namePrefix: dev-

commonLabels:
  environment: dev
  app: guestbook

bases:
  - ../../base

replicas:
  - name: guestbook-ui
    count: 2

configMapGenerator:
  - name: guestbook-config
    literals:
      - ENVIRONMENT=development