apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

namePrefix: prod-

commonLabels:
  environment: prod
  app: guestbook

bases:
  - ../../base

replicas:
  - name: guestbook-ui
    count: 3

configMapGenerator:
  - name: guestbook-config
    literals:
      - ENVIRONMENT=production